import React, { useState } from "react";

function AddUnit() {
  const [unitName, setUnitName] = useState("");
  const [unitCode] = useState("#0001254632");

  // Handle form submission
  const handleAddUnit = () => {
    console.log("Unit added successfully!");
  };

  return (
    <div className="container mx-auto p-6">
      <div className="bg-white rounded-lg shadow-lg p-6 mt-4">
        <div>
          <h2 className="text-2xl font-bold text-green-700 mb-6">Add Unit</h2>
          {/* Left Column */}
          <div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">Unit Name</label>
              <input
                type="text"
                className="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
                placeholder="Enter unit name"
                value={unitName}
                onChange={(e) => setUnitName(e.target.value)}
              />
            </div>
          </div>
          <div className="mb-4">
            <label className="block text-gray-700 mb-2">Unit Code</label>
            <div className="flex items-center">
              <input
                type="text"
                className="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
                value={unitCode}
                readOnly
              />
              <button className="ml-4 p-3 bg-gray-200 rounded-lg hover:bg-gray-300">
                <span className="text-gray-700">Edit</span>
              </button>
            </div>
            <p className="text-sm text-gray-500 mt-2">
              This is a unit code auto-generated by the system. It can be
              changed at any time.
            </p>
          </div>
        </div>
      </div>

      <div className="flex space-x-4 mt-6">
        <button
          className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700"
          onClick={handleAddUnit}
        >
          Add Unit
        </button>
        <button className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">
          Save Unit
        </button>
      </div>
    </div>
  );
}

export default AddUnit;
